version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: example
      POSTGRES_PASSWORD: example2022
      POSTGRES_DB: test-microservice-ordered
      PGDATA: /data/postgres
    ports:
      - '5434:5432'