version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: example
      POSTGRES_PASSWORD: example2022
      POSTGRES_DB: microserviceone
      PGDATA: /data/postgres
    ports:
      - '5432:5432'
    volumes: 
      - ./db:/data/postgres