version: '3'

services:
  db-mysql:
    image: mysql:5.7
    environment:
      MYSQL_USER: example1
      MYSQL_PASSWORD: example2022
      MYSQL_ROOT_PASSWORD: example2022
      MYSQL_DATABASE: test-microservice-products
    ports:
      - '3308:3306'